package com.example.graduationproject.ui

enum class ServixScreens {
    OnBoarding,
    Login,
    FirstSignup,
    SecondSignup,
    ForgotPassword,
    ResetPassword,
    AfterPassword,
    Otp,
    Test,
    BeforeSignup,
    SignupThird,
    ProviderAccountInfo,
    ProviderAccountInfoDetails,
    UserAccountInfo,
    UserAccountInfoDetails,
    Settings,
    NewPassword,
    Home,
    Notification,
    ShareProblemScreen,
    Favorite,
FindProvider,
    ViewProfile,
    ProviderHome,
    PostDetails,
    AddNeWorkToProfileItems,
    NewPasswordScreen,
    NotifiPostItemDetailByID,

}